### PR TITLE
Translate more page to Persian

### PR DESCRIPTION
**Pull request by BaseMax**
Hello,

Thank you for your help @sorousht. https://github.com/reactjs/fa.reactjs.org/issues/105

Pages until now:
- fragments.md
- reference-react-dom.md
- forwarding-refs.md (incomplete)

Best,
Max Base

### CODE REVIEW

**Comment by sorousht** [comment]
Hi @BaseMax 

Thanks for translating these pages.
I just assigned [Fragments](https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/fragments.md) to you here #1. This is how we manage translations. The contributors usually leave a comment here #1 to ask if their desired page is available first.

Unfortunately, `content/docs/reference-react-dom.md` was assigned to @Abolfazl2647 previously. I forgot to add the label `assigned` to issue #105 in order to prevent any confusion. There is an open PR #126 for that page.

Every PR should contain only one page. This makes it easier to manage the PRs and review them. Can you please submit a new PR for `Fragments`?

Then we find a way to use your translation of reference-react-dom.md later on.

Thank you again,
Soroush

**Comment by BaseMax** [comment]
Dear @sorousht,

Sorry, But this was a problem.
He did not mention it at Issue page. https://github.com/reactjs/fa.reactjs.org/issues/105

I close this PR, I will create one by one pages in new seperate PR.

Sorry for my mistake. :sob: 
Please be here for fast review. :+1: 
Thank you :heart: 

Best,
Max

**Comment by sorousht** [comment]
I've to mention that you would better have only one page in-progress. This means you should wait for your first PR to be reviewed, and then you'll be given another page.

**Comment by sorousht** [comment]
Dear @BaseMax 

It was actually my mistake and I apologize for that. We will definitely use your effort to improve the translation of `reference-react-dom.md`. First, let's just focus on [Fragments](https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/fragments.md).

Thanks,
Soroush

**Pull request closed without merging**
