### PR TITLE
React without ES6 translated

### PR DESCRIPTION
**Pull request by hosseinAMD**
Dear @sorousht 

Take your time to review this page!
Good luck!

### CODE REVIEW

**Comment by hosseinAMD** [comment]
@sorousht 
I can't understand the problem of tests failing.
I've done steps like other pages and only translated .md file
Can you check why the tests are failing?

**Steps**
```
git fetch upstream
git merge upstream/master
git checkout -b [branch-name]
git status
git add .
git commit -m "message"
git merge [branch-name]
git push origin [branch-name]
```

**Review by sorousht — APPROVED** [review]
مثل همیشه عالی بود @hosseinAMD جان!

**Comment by sorousht** [comment]
بررسی می کنم ببینم مشکل از چیه!

**Comment by sorousht** [comment]
پول ریکوست قبول و ادغام شد!

**Pull request merged**
