### PR TITLE
React.Component translated

### PR DESCRIPTION
**Pull request by hosseinAMD**
Finally!!!
This page was so long and Hard! :D
with many important aspects of translation because some sentences weren't understandable in Persian, So I've changed some of them regard to their content and purpose.
Thanks again!

P.S: I've updated my keyboard layout so Half-Space and other Persian characters shouldn't be a problem from now on!

### CODE REVIEW

**Comment by sorousht** [comment]
Great job @hosseinAMD!

Please give me some time to review it :sweat_smile:

**Comment by hosseinAMD** [comment]
> 
> 
> Great job @hosseinAMD!
> 
> Please give me some time to review it 😅

@sorousht 
Hi soroush
First, Thank you for your efforts
Second, I wonder to know if any advance happened in reviewing this page?

**Comment by sorousht** [comment]
Hi @hosseinAMD 
Thank you for collaborating as well!
I try to find some free time during the week to start reviewing this PR, but usually, I spend some time on weekends.
Would you like to start a new page in the meanwhile?

**Comment by hosseinAMD** [comment]
> 
> 
> Hi @hosseinAMD
> Thank you for collaborating as well!
> I try to find some free time during the week to start reviewing this PR, but usually, I spend some time on weekends.
> Would you like to start a new page in the meanwhile?

Sure i can do it...
I will post a comment on Issue 1!

**Comment by hosseinAMD** [comment]
@sorousht 

I don't know it's correct or not but github merged my new translation pull request with this!
Anyway, here is my new translation file!

**Comment by sorousht** [comment]
have you used a single branch for both PRs?

**Comment by hosseinAMD** [comment]
> 
> 
> have you used a single branch for both PRs?

@sorousht 

No. I've used 2 different branches

**Comment by sorousht** [comment]
Screenshot from 2020-07-02 09 21 33

The PR shows that you pushed your commits into branch `master` of your clone. You need two branches in which you have the changes only one page. If you need help for that, let me know :)

**Comment by hosseinAMD** [comment]
> 
> 
> Screenshot from 2020-07-02 09 21 33
> 
> The PR shows that you pushed your commits into branch `master` of your clone. You need two branches in which you have the changes only one page. If you need help for that, let me know :)

I've merged them in my local repo after pushing by ingle branches!
Let me take a look

**Comment by hosseinAMD** [comment]
> 
> 
> > Screenshot from 2020-07-02 09 21 33
> > The PR shows that you pushed your commits into branch `master` of your clone. You need two branches in which you have the changes only one page. If you need help for that, let me know :)
> 
> I've merged them in my local repo after pushing by ingle branches!
> Let me take a look

Created a different pull request for test utils... do you need a new one for here too?

**Comment by sorousht** [comment]
Now you have 2 PRs, both having the same changes. In this one, the changes of `content/docs/addons-test-utils.md` should be reverted. For #156, the changes of `content/docs/reference-react-component.md` should be reverted. In result, you will have 2 PRs each containing only changes of one file.

**Pull request closed without merging**
